FROM docker.io/alpine:3.22

USER root
RUN apk add linux-headers
RUN apk add poppler-utils
RUN apk add sqlite sqlite-libs sqlite-dev sqlite-static
RUN apk add sqlite-analyzer
RUN apk add make
RUN apk add clang
RUN apk add opam
RUN apk add git
RUN apk add python3

# RUN ln -s $(which opam-2.2) /usr/local/bin/opam
RUN opam --version
RUN apk add bash
RUN opam init --disable-sandboxing
RUN opam install --yes dune
RUN opam install --yes utop ocp-indent

COPY . /root/docfd
# RUN chown -R root:root /home/opam/docfd

WORKDIR /root/docfd
RUN eval $(opam env) && dune build docfd.opam
RUN opam install --yes . --deps-only --with-test
RUN echo 'eval $(opam env)' >> /root/.bash_profile
