FROM docker.io/ocaml/opam:alpine-ocaml-5.2

USER root
RUN apk add linux-headers
RUN apk add poppler-utils

USER opam
RUN sudo ln -s $(which opam-2.2) /usr/local/bin/opam
RUN opam init --disable-sandboxing
SHELL ["/bin/bash", "--login" , "-c"]
RUN opam install dune
RUN opam install utop ocp-indent

USER root
COPY . /home/opam/docfd
RUN chown -R opam:opam /home/opam/docfd

USER opam
WORKDIR /home/opam/docfd
RUN dune build docfd.opam
RUN opam install . --deps-only --with-test
