FROM docker.io/ocaml/opam:alpine-ocaml-5.1

USER root
RUN apk add linux-headers
RUN apk add poppler-utils

USER opam
RUN opam init --disable-sandboxing
RUN opam install dune containers fmt
RUN opam install utop ocp-indent
RUN opam install cmdliner
RUN opam install angstrom
RUN opam install spelll
RUN opam install notty
RUN opam install oseq
RUN opam install eio
RUN opam install eio_main
RUN opam install domainslib
RUN opam install kcas_data
RUN opam install yojson
RUN opam install digestif
RUN opam install containers-data
RUN opam pin add nottui https://github.com/let-def/lwd.git#a337a778001e6c1dbaed7e758c9e05f300abd388
