Output demo-vhs-gifs/pdf.gif
Set Padding 0
Set Framerate 10

Set Width  1024
Set Height  768
Set FontSize 15

Set TypingSpeed 100ms

Type@80ms "docfd --cache-dir .cache ocaml_programming.pdf # pdf is indexed beforehand"
Enter

Sleep 3s

Type "/"
Type "recursive case"
Enter
Sleep 1s
Type "j"
Sleep 1s
Type "j"
Sleep 2s

Type "x"
Type "/"
Type "list inductive"
Enter
Sleep 1s
Type "j"
Sleep 1s
Type "j"
Sleep 2s

Type "q"
