Output demo-vhs-gifs/repo.gif
Set Padding 0
Set Framerate 10

Set Width  1024
Set Height  768
Set FontSize 15

Set TypingSpeed 100ms

Type@50ms "docfd --cache-dir .cache --exts md --max-depth 1 # using a local cache for demo"
Enter

Sleep 1s

Type "j"
Sleep 1s
Type "k"
Sleep 1s

Type "/"
Type "Fuzy search"
Enter
Sleep 1s

Type "J"
Sleep 1s
Type "K"
Sleep 1s

Tab
Sleep 1s

Tab
Sleep 1s

Enter
Down@0.1s 30
Sleep 1s
Type@200ms ":q"
Enter

Sleep 2s
